### PR TITLE
Added Chinese(simplified) Translation

### PR DESCRIPTION
**Pull request by Antares95**

### CODE REVIEW

**Comment by KonstantinShtepa** [comment]
Hello!
Big thanks for your translation! )
Did you test it and it work?

There few things in your commit because of which I cannot merge it in current state. 
1) Commit shouldn't change other translation files
2) .pot file also doesn't need to be included in commit if the only chage in it is creation date
3) By some reason structure of you .po file is mitmatches with structure of other .po files. Please, change it so it would match.
4) .mo file is not updated.
I updated translation guide so it would mention all these situations.

Also, about translation: "mie" is default short name of week day(from spannish "miércoles"(eng. wednesday) - Don't ask why would Dhabyx set default day of week to wednesday - idk, you can change it to monday in chinese), and "dic" is default short name of mounth(from spannich "diciembre"(eng. December)). I would change them someday(after merging language commits) to match "mon"(monday) and "jan"(january).

I would appreciate if you rewrite your merge request according with stated above.

**Comment by Antares95** [comment]
Hello!
The .pot file and other .po seem modify by my misoperation.
I will rewrite my merge request soon.
Thank for you reply. :)

**Comment by Antares95** [comment]
I rewrited the merge request.
It test in my PC and work good. :)

screenshot_20170405_180043

**Comment by KonstantinShtepa** [comment]
Looks good to me. Merging.

**Pull request merged**
