### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by SeeLook**
Sorry for messy previous pull request. 
This time should be fine

### CODE REVIEW

**Comment by KonstantinShtepa** [comment]
It's ok. You can always update request. There no reason to close and open new one. Pull request is not about commits, it about merge one branch(SeeLook:master) into other branch(dhabyx:master).
And sorry, but I cannot merge this request as well because of ".po" file structure mismatch. =)
Just do this:
1) run translations/Messages.sh and you will see that it will change ".mo" and ".po" files(because structure of translation in ".po" file is messed up).
2) commit these two files to your SeeLook:master github repo. After that they will appear there. I will sqeeze them and merge them as one. Or you can amend your last commit and rewrite it contains(if you know how to amend).

**Comment by KonstantinShtepa** [comment]
Also, in second commit you can mention in it's messages "closes #12". That way it will automatically close your issue.

**Comment by SeeLook** [comment]
Thanks for patience. I never work with git in a team (just myself and rarely)
I'm just invoking Messages.sh but it is not updating *.po file of Polish translations (only others).
During translation I opened that *po either with QtLinquist and Lokalize and I just realized the they reordering texts everyone with its own way. Probably this is why it doesn't match with base untranslated version order. But it has no any influence on *.mo file.

**Comment by SeeLook** [comment]
Ok, I see, lokalize added some extra headers into po file, Should I remove them?
Order of texts is correct.

**Comment by KonstantinShtepa** [comment]
Order of text is incorrect. Just see .pot file for example. 
Just use files from there https://yadi.sk/d/dtIl8qcP3GhMu8

**Comment by SeeLook** [comment]
I tried to amend those files to the last commit but git complains about conflicts.
I'm too blind at this time to learn more about git, so please add them to Your repo directly, I will fork it once more tomorrow with fresh brain :)

**Comment by KonstantinShtepa** [comment]
It's ok. You can always push them into new commit.

**Comment by KonstantinShtepa** [comment]
Looks good to me. Thantks for patch! :+1: :) Squashing and merging.

**Pull request merged**
